default: &default
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  password:
  username: postgres

development:
  <<: *default
  database: carrot-development

test:
  <<: *default
  database: carrot-test
